from __future__ import annotations

from typing import Final

TOTAL_MAINLAND_MUNICIPALITIES: Final[int] = 4
TOTAL_PRC_PREFECTURE_LEVEL_CITIES: Final[int] = 293

# Curated mainland China city coverage for the historical data agent.
# The list covers all 31 mainland province-level regions and is intentionally
# limited to municipalities and prefecture-level cities, excluding county-level cities.
# Coverage exceeds 50% of the 293 prefecture-level cities while prioritizing
# provincial capitals and major tier-1 / tier-2 cities.
MAINLAND_CHINA_CITY_ROWS: Final[tuple[tuple[str, str, str | None], ...]] = (
    ("Anhui", "Anqing", None),
    ("Anhui", "Bengbu", None),
    ("Anhui", "Chuzhou", None),
    ("Anhui", "Fuyang", None),
    ("Anhui", "Hefei", None),
    ("Anhui", "Huangshan", None),
    ("Anhui", "Lu'an", None),
    ("Anhui", "Ma'anshan", None),
    ("Anhui", "Wuhu", None),
    ("Anhui", "Xuancheng", None),
    ("Beijing Municipality", "Beijing", None),
    ("Chongqing Municipality", "Chongqing", None),
    ("Fujian", "Fuzhou", None),
    ("Fujian", "Longyan", None),
    ("Fujian", "Nanping", None),
    ("Fujian", "Ningde", None),
    ("Fujian", "Putian", None),
    ("Fujian", "Quanzhou", None),
    ("Fujian", "Sanming", None),
    ("Fujian", "Xiamen", None),
    ("Fujian", "Zhangzhou", None),
    ("Gansu", "Baiyin", None),
    ("Gansu", "Jiayuguan", None),
    ("Gansu", "Jiuquan", None),
    ("Gansu", "Lanzhou", None),
    ("Gansu", "Qingyang", None),
    ("Gansu", "Tianshui", None),
    ("Gansu", "Wuwei", None),
    ("Gansu", "Zhangye", None),
    ("Guangdong", "Chaozhou", None),
    ("Guangdong", "Dongguan", None),
    ("Guangdong", "Foshan", None),
    ("Guangdong", "Guangzhou", None),
    ("Guangdong", "Heyuan", None),
    ("Guangdong", "Huizhou", None),
    ("Guangdong", "Jiangmen", None),
    ("Guangdong", "Jieyang", None),
    ("Guangdong", "Maoming", None),
    ("Guangdong", "Meizhou", None),
    ("Guangdong", "Qingyuan", None),
    ("Guangdong", "Shantou", None),
    ("Guangdong", "Shanwei", None),
    ("Guangdong", "Shaoguan", None),
    ("Guangdong", "Shenzhen", None),
    ("Guangdong", "Yangjiang", None),
    ("Guangdong", "Yunfu", None),
    ("Guangdong", "Zhanjiang", None),
    ("Guangdong", "Zhaoqing", None),
    ("Guangdong", "Zhongshan", None),
    ("Guangdong", "Zhuhai", None),
    ("Guangxi", "Baise", None),
    ("Guangxi", "Beihai", None),
    ("Guangxi", "Chongzuo", None),
    ("Guangxi", "Fangchenggang", None),
    ("Guangxi", "Guilin", None),
    ("Guangxi", "Guigang", None),
    ("Guangxi", "Hezhou", None),
    ("Guangxi", "Laibin", None),
    ("Guangxi", "Liuzhou", None),
    ("Guangxi", "Nanning", None),
    ("Guangxi", "Qinzhou", None),
    ("Guangxi", "Wuzhou", None),
    ("Guangxi", "Yulin", None),
    ("Guizhou", "Anshun", None),
    ("Guizhou", "Bijie", None),
    ("Guizhou", "Guiyang", None),
    ("Guizhou", "Liupanshui", None),
    ("Guizhou", "Tongren", None),
    ("Guizhou", "Zunyi", None),
    ("Hainan", "Danzhou", None),
    ("Hainan", "Haikou", None),
    ("Hainan", "Sanya", None),
    ("Hebei", "Baoding", None),
    ("Hebei", "Cangzhou", None),
    ("Hebei", "Handan", None),
    ("Hebei", "Langfang", None),
    ("Hebei", "Qinhuangdao", None),
    ("Hebei", "Shijiazhuang", None),
    ("Hebei", "Tangshan", None),
    ("Hebei", "Xingtai", None),
    ("Heilongjiang", "Daqing", None),
    ("Heilongjiang", "Harbin", None),
    ("Heilongjiang", "Heihe", None),
    ("Heilongjiang", "Jiamusi", None),
    ("Heilongjiang", "Mudanjiang", None),
    ("Heilongjiang", "Qiqihar", None),
    ("Heilongjiang", "Yichun", None),
    ("Henan", "Anyang", None),
    ("Henan", "Jiaozuo", None),
    ("Henan", "Kaifeng", None),
    ("Henan", "Luoyang", None),
    ("Henan", "Luohe", None),
    ("Henan", "Nanyang", None),
    ("Henan", "Pingdingshan", None),
    ("Henan", "Shangqiu", None),
    ("Henan", "Xinxiang", None),
    ("Henan", "Xuchang", None),
    ("Henan", "Zhengzhou", None),
    ("Henan", "Zhoukou", None),
    ("Henan", "Zhumadian", None),
    ("Hubei", "Ezhou", None),
    ("Hubei", "Huangshi", None),
    ("Hubei", "Jingmen", None),
    ("Hubei", "Jingzhou", None),
    ("Hubei", "Shiyan", None),
    ("Hubei", "Wuhan", None),
    ("Hubei", "Xiangyang", None),
    ("Hubei", "Xiaogan", None),
    ("Hubei", "Yichang", None),
    ("Hunan", "Changde", None),
    ("Hunan", "Changsha", None),
    ("Hunan", "Chenzhou", None),
    ("Hunan", "Hengyang", None),
    ("Hunan", "Huaihua", None),
    ("Hunan", "Loudi", None),
    ("Hunan", "Shaoyang", None),
    ("Hunan", "Xiangtan", None),
    ("Hunan", "Yiyang", None),
    ("Hunan", "Yueyang", None),
    ("Hunan", "Zhuzhou", None),
    ("Inner Mongolia", "Baotou", None),
    ("Inner Mongolia", "Chifeng", None),
    ("Inner Mongolia", "Hohhot", None),
    ("Inner Mongolia", "Hulunbuir", None),
    ("Inner Mongolia", "Ordos", None),
    ("Inner Mongolia", "Tongliao", None),
    ("Inner Mongolia", "Ulanqab", None),
    ("Inner Mongolia", "Wuhai", None),
    ("Jiangsu", "Changzhou", None),
    ("Jiangsu", "Huaian", None),
    ("Jiangsu", "Lianyungang", None),
    ("Jiangsu", "Nanjing", None),
    ("Jiangsu", "Nantong", None),
    ("Jiangsu", "Suqian", None),
    ("Jiangsu", "Suzhou", None),
    ("Jiangsu", "Taizhou", None),
    ("Jiangsu", "Wuxi", None),
    ("Jiangsu", "Xuzhou", None),
    ("Jiangsu", "Yancheng", None),
    ("Jiangsu", "Yangzhou", None),
    ("Jiangsu", "Zhenjiang", None),
    ("Jiangxi", "Ganzhou", None),
    ("Jiangxi", "Jingdezhen", None),
    ("Jiangxi", "Jiujiang", None),
    ("Jiangxi", "Nanchang", None),
    ("Jiangxi", "Pingxiang", None),
    ("Jiangxi", "Shangrao", None),
    ("Jiangxi", "Xinyu", None),
    ("Jiangxi", "Yichun", None),
    ("Jilin", "Baicheng", None),
    ("Jilin", "Changchun", None),
    ("Jilin", "Jilin", None),
    ("Jilin", "Liaoyuan", None),
    ("Jilin", "Siping", None),
    ("Jilin", "Tonghua", None),
    ("Liaoning", "Anshan", None),
    ("Liaoning", "Benxi", None),
    ("Liaoning", "Dalian", None),
    ("Liaoning", "Fushun", None),
    ("Liaoning", "Jinzhou", None),
    ("Liaoning", "Shenyang", None),
    ("Liaoning", "Yingkou", None),
    ("Ningxia", "Guyuan", None),
    ("Ningxia", "Shizuishan", None),
    ("Ningxia", "Wuzhong", None),
    ("Ningxia", "Yinchuan", None),
    ("Ningxia", "Zhongwei", None),
    ("Qinghai", "Haidong", None),
    ("Qinghai", "Xining", None),
    ("Shaanxi", "Ankang", None),
    ("Shaanxi", "Baoji", None),
    ("Shaanxi", "Hanzhong", None),
    ("Shaanxi", "Shangluo", None),
    ("Shaanxi", "Tongchuan", None),
    ("Shaanxi", "Weinan", None),
    ("Shaanxi", "Xi'an", "Xian"),
    ("Shaanxi", "Xianyang", None),
    ("Shaanxi", "Yan'an", None),
    ("Shaanxi", "Yulin", None),
    ("Shandong", "Binzhou", None),
    ("Shandong", "Dezhou", None),
    ("Shandong", "Dongying", None),
    ("Shandong", "Heze", None),
    ("Shandong", "Jinan", None),
    ("Shandong", "Jining", None),
    ("Shandong", "Liaocheng", None),
    ("Shandong", "Linyi", None),
    ("Shandong", "Qingdao", None),
    ("Shandong", "Rizhao", None),
    ("Shandong", "Tai'an", None),
    ("Shandong", "Weifang", None),
    ("Shandong", "Weihai", None),
    ("Shandong", "Yantai", None),
    ("Shandong", "Zibo", None),
    ("Shanghai Municipality", "Shanghai", None),
    ("Shanxi", "Changzhi", None),
    ("Shanxi", "Datong", None),
    ("Shanxi", "Jincheng", None),
    ("Shanxi", "Linfen", None),
    ("Shanxi", "Taiyuan", None),
    ("Shanxi", "Yuncheng", None),
    ("Sichuan", "Chengdu", None),
    ("Sichuan", "Deyang", None),
    ("Sichuan", "Leshan", None),
    ("Sichuan", "Luzhou", None),
    ("Sichuan", "Meishan", None),
    ("Sichuan", "Mianyang", None),
    ("Sichuan", "Nanchong", None),
    ("Sichuan", "Yaan", "Ya'an"),
    ("Sichuan", "Yibin", None),
    ("Sichuan", "Zigong", None),
    ("Tianjin Municipality", "Tianjin", None),
    ("Tibet", "Chamdo", None),
    ("Tibet", "Lhasa", None),
    ("Tibet", "Nagqu", None),
    ("Tibet", "Nyingchi", None),
    ("Tibet", "Shannan", None),
    ("Tibet", "Shigatse", None),
    ("Xinjiang", "Hami", None),
    ("Xinjiang", "Karamay", None),
    ("Xinjiang", "Turpan", None),
    ("Xinjiang", "Urumqi", None),
    ("Yunnan", "Baoshan", None),
    ("Yunnan", "Kunming", None),
    ("Yunnan", "Lijiang", None),
    ("Yunnan", "Lincang", None),
    ("Yunnan", "Pu'er", None),
    ("Yunnan", "Qujing", None),
    ("Yunnan", "Yuxi", None),
    ("Yunnan", "Zhaotong", None),
    ("Zhejiang", "Hangzhou", None),
    ("Zhejiang", "Huzhou", None),
    ("Zhejiang", "Jiaxing", None),
    ("Zhejiang", "Jinhua", None),
    ("Zhejiang", "Lishui", None),
    ("Zhejiang", "Ningbo", None),
    ("Zhejiang", "Quzhou", None),
    ("Zhejiang", "Shaoxing", None),
    ("Zhejiang", "Taizhou", None),
    ("Zhejiang", "Wenzhou", None),
    ("Zhejiang", "Zhoushan", None),
)

MAINLAND_CHINA_PROVINCE_DISPLAY_NAMES: Final[dict[str, str]] = {
    "Anhui": "安徽省",
    "Beijing Municipality": "北京市",
    "Chongqing Municipality": "重庆市",
    "Fujian": "福建省",
    "Gansu": "甘肃省",
    "Guangdong": "广东省",
    "Guangxi": "广西壮族自治区",
    "Guizhou": "贵州省",
    "Hainan": "海南省",
    "Hebei": "河北省",
    "Heilongjiang": "黑龙江省",
    "Henan": "河南省",
    "Hubei": "湖北省",
    "Hunan": "湖南省",
    "Inner Mongolia": "内蒙古自治区",
    "Jiangsu": "江苏省",
    "Jiangxi": "江西省",
    "Jilin": "吉林省",
    "Liaoning": "辽宁省",
    "Ningxia": "宁夏回族自治区",
    "Qinghai": "青海省",
    "Shaanxi": "陕西省",
    "Shandong": "山东省",
    "Shanghai Municipality": "上海市",
    "Shanxi": "山西省",
    "Sichuan": "四川省",
    "Tianjin Municipality": "天津市",
    "Tibet": "西藏自治区",
    "Xinjiang": "新疆维吾尔自治区",
    "Yunnan": "云南省",
    "Zhejiang": "浙江省",
}

MAINLAND_CHINA_CITY_DISPLAY_NAMES: Final[dict[tuple[str, str], str]] = {
    ("Anhui", "Anqing"): "安庆",
    ("Anhui", "Bengbu"): "蚌埠",
    ("Anhui", "Chuzhou"): "滁州",
    ("Anhui", "Fuyang"): "阜阳",
    ("Anhui", "Hefei"): "合肥",
    ("Anhui", "Huangshan"): "黄山",
    ("Anhui", "Lu'an"): "六安",
    ("Anhui", "Ma'anshan"): "马鞍山",
    ("Anhui", "Wuhu"): "芜湖",
    ("Anhui", "Xuancheng"): "宣城",
    ("Beijing Municipality", "Beijing"): "北京",
    ("Chongqing Municipality", "Chongqing"): "重庆",
    ("Fujian", "Fuzhou"): "福州",
    ("Fujian", "Longyan"): "龙岩",
    ("Fujian", "Nanping"): "南平",
    ("Fujian", "Ningde"): "宁德",
    ("Fujian", "Putian"): "莆田",
    ("Fujian", "Quanzhou"): "泉州",
    ("Fujian", "Sanming"): "三明",
    ("Fujian", "Xiamen"): "厦门",
    ("Fujian", "Zhangzhou"): "漳州",
    ("Gansu", "Baiyin"): "白银",
    ("Gansu", "Jiayuguan"): "嘉峪关",
    ("Gansu", "Jiuquan"): "酒泉",
    ("Gansu", "Lanzhou"): "兰州",
    ("Gansu", "Qingyang"): "庆阳",
    ("Gansu", "Tianshui"): "天水",
    ("Gansu", "Wuwei"): "武威",
    ("Gansu", "Zhangye"): "张掖",
    ("Guangdong", "Chaozhou"): "潮州",
    ("Guangdong", "Dongguan"): "东莞",
    ("Guangdong", "Foshan"): "佛山",
    ("Guangdong", "Guangzhou"): "广州",
    ("Guangdong", "Heyuan"): "河源",
    ("Guangdong", "Huizhou"): "惠州",
    ("Guangdong", "Jiangmen"): "江门",
    ("Guangdong", "Jieyang"): "揭阳",
    ("Guangdong", "Maoming"): "茂名",
    ("Guangdong", "Meizhou"): "梅州",
    ("Guangdong", "Qingyuan"): "清远",
    ("Guangdong", "Shantou"): "汕头",
    ("Guangdong", "Shanwei"): "汕尾",
    ("Guangdong", "Shaoguan"): "韶关",
    ("Guangdong", "Shenzhen"): "深圳",
    ("Guangdong", "Yangjiang"): "阳江",
    ("Guangdong", "Yunfu"): "云浮",
    ("Guangdong", "Zhanjiang"): "湛江",
    ("Guangdong", "Zhaoqing"): "肇庆",
    ("Guangdong", "Zhongshan"): "中山",
    ("Guangdong", "Zhuhai"): "珠海",
    ("Guangxi", "Baise"): "百色",
    ("Guangxi", "Beihai"): "北海",
    ("Guangxi", "Chongzuo"): "崇左",
    ("Guangxi", "Fangchenggang"): "防城港",
    ("Guangxi", "Guilin"): "桂林",
    ("Guangxi", "Guigang"): "贵港",
    ("Guangxi", "Hezhou"): "贺州",
    ("Guangxi", "Laibin"): "来宾",
    ("Guangxi", "Liuzhou"): "柳州",
    ("Guangxi", "Nanning"): "南宁",
    ("Guangxi", "Qinzhou"): "钦州",
    ("Guangxi", "Wuzhou"): "梧州",
    ("Guangxi", "Yulin"): "玉林",
    ("Guizhou", "Anshun"): "安顺",
    ("Guizhou", "Bijie"): "毕节",
    ("Guizhou", "Guiyang"): "贵阳",
    ("Guizhou", "Liupanshui"): "六盘水",
    ("Guizhou", "Tongren"): "铜仁",
    ("Guizhou", "Zunyi"): "遵义",
    ("Hainan", "Danzhou"): "儋州",
    ("Hainan", "Haikou"): "海口",
    ("Hainan", "Sanya"): "三亚",
    ("Hebei", "Baoding"): "保定",
    ("Hebei", "Cangzhou"): "沧州",
    ("Hebei", "Handan"): "邯郸",
    ("Hebei", "Langfang"): "廊坊",
    ("Hebei", "Qinhuangdao"): "秦皇岛",
    ("Hebei", "Shijiazhuang"): "石家庄",
    ("Hebei", "Tangshan"): "唐山",
    ("Hebei", "Xingtai"): "邢台",
    ("Heilongjiang", "Daqing"): "大庆",
    ("Heilongjiang", "Harbin"): "哈尔滨",
    ("Heilongjiang", "Heihe"): "黑河",
    ("Heilongjiang", "Jiamusi"): "佳木斯",
    ("Heilongjiang", "Mudanjiang"): "牡丹江",
    ("Heilongjiang", "Qiqihar"): "齐齐哈尔",
    ("Heilongjiang", "Yichun"): "伊春",
    ("Henan", "Anyang"): "安阳",
    ("Henan", "Jiaozuo"): "焦作",
    ("Henan", "Kaifeng"): "开封",
    ("Henan", "Luoyang"): "洛阳",
    ("Henan", "Luohe"): "漯河",
    ("Henan", "Nanyang"): "南阳",
    ("Henan", "Pingdingshan"): "平顶山",
    ("Henan", "Shangqiu"): "商丘",
    ("Henan", "Xinxiang"): "新乡",
    ("Henan", "Xuchang"): "许昌",
    ("Henan", "Zhengzhou"): "郑州",
    ("Henan", "Zhoukou"): "周口",
    ("Henan", "Zhumadian"): "驻马店",
    ("Hubei", "Ezhou"): "鄂州",
    ("Hubei", "Huangshi"): "黄石",
    ("Hubei", "Jingmen"): "荆门",
    ("Hubei", "Jingzhou"): "荆州",
    ("Hubei", "Shiyan"): "十堰",
    ("Hubei", "Wuhan"): "武汉",
    ("Hubei", "Xiangyang"): "襄阳",
    ("Hubei", "Xiaogan"): "孝感",
    ("Hubei", "Yichang"): "宜昌",
    ("Hunan", "Changde"): "常德",
    ("Hunan", "Changsha"): "长沙",
    ("Hunan", "Chenzhou"): "郴州",
    ("Hunan", "Hengyang"): "衡阳",
    ("Hunan", "Huaihua"): "怀化",
    ("Hunan", "Loudi"): "娄底",
    ("Hunan", "Shaoyang"): "邵阳",
    ("Hunan", "Xiangtan"): "湘潭",
    ("Hunan", "Yiyang"): "益阳",
    ("Hunan", "Yueyang"): "岳阳",
    ("Hunan", "Zhuzhou"): "株洲",
    ("Inner Mongolia", "Baotou"): "包头",
    ("Inner Mongolia", "Chifeng"): "赤峰",
    ("Inner Mongolia", "Hohhot"): "呼和浩特",
    ("Inner Mongolia", "Hulunbuir"): "呼伦贝尔",
    ("Inner Mongolia", "Ordos"): "鄂尔多斯",
    ("Inner Mongolia", "Tongliao"): "通辽",
    ("Inner Mongolia", "Ulanqab"): "乌兰察布",
    ("Inner Mongolia", "Wuhai"): "乌海",
    ("Jiangsu", "Changzhou"): "常州",
    ("Jiangsu", "Huaian"): "淮安",
    ("Jiangsu", "Lianyungang"): "连云港",
    ("Jiangsu", "Nanjing"): "南京",
    ("Jiangsu", "Nantong"): "南通",
    ("Jiangsu", "Suqian"): "宿迁",
    ("Jiangsu", "Suzhou"): "苏州",
    ("Jiangsu", "Taizhou"): "泰州",
    ("Jiangsu", "Wuxi"): "无锡",
    ("Jiangsu", "Xuzhou"): "徐州",
    ("Jiangsu", "Yancheng"): "盐城",
    ("Jiangsu", "Yangzhou"): "扬州",
    ("Jiangsu", "Zhenjiang"): "镇江",
    ("Jiangxi", "Ganzhou"): "赣州",
    ("Jiangxi", "Jingdezhen"): "景德镇",
    ("Jiangxi", "Jiujiang"): "九江",
    ("Jiangxi", "Nanchang"): "南昌",
    ("Jiangxi", "Pingxiang"): "萍乡",
    ("Jiangxi", "Shangrao"): "上饶",
    ("Jiangxi", "Xinyu"): "新余",
    ("Jiangxi", "Yichun"): "宜春",
    ("Jilin", "Baicheng"): "白城",
    ("Jilin", "Changchun"): "长春",
    ("Jilin", "Jilin"): "吉林",
    ("Jilin", "Liaoyuan"): "辽源",
    ("Jilin", "Siping"): "四平",
    ("Jilin", "Tonghua"): "通化",
    ("Liaoning", "Anshan"): "鞍山",
    ("Liaoning", "Benxi"): "本溪",
    ("Liaoning", "Dalian"): "大连",
    ("Liaoning", "Fushun"): "抚顺",
    ("Liaoning", "Jinzhou"): "锦州",
    ("Liaoning", "Shenyang"): "沈阳",
    ("Liaoning", "Yingkou"): "营口",
    ("Ningxia", "Guyuan"): "固原",
    ("Ningxia", "Shizuishan"): "石嘴山",
    ("Ningxia", "Wuzhong"): "吴忠",
    ("Ningxia", "Yinchuan"): "银川",
    ("Ningxia", "Zhongwei"): "中卫",
    ("Qinghai", "Haidong"): "海东",
    ("Qinghai", "Xining"): "西宁",
    ("Shaanxi", "Ankang"): "安康",
    ("Shaanxi", "Baoji"): "宝鸡",
    ("Shaanxi", "Hanzhong"): "汉中",
    ("Shaanxi", "Shangluo"): "商洛",
    ("Shaanxi", "Tongchuan"): "铜川",
    ("Shaanxi", "Weinan"): "渭南",
    ("Shaanxi", "Xi'an"): "西安",
    ("Shaanxi", "Xianyang"): "咸阳",
    ("Shaanxi", "Yan'an"): "延安",
    ("Shaanxi", "Yulin"): "榆林",
    ("Shandong", "Binzhou"): "滨州",
    ("Shandong", "Dezhou"): "德州",
    ("Shandong", "Dongying"): "东营",
    ("Shandong", "Heze"): "菏泽",
    ("Shandong", "Jinan"): "济南",
    ("Shandong", "Jining"): "济宁",
    ("Shandong", "Liaocheng"): "聊城",
    ("Shandong", "Linyi"): "临沂",
    ("Shandong", "Qingdao"): "青岛",
    ("Shandong", "Rizhao"): "日照",
    ("Shandong", "Tai'an"): "泰安",
    ("Shandong", "Weifang"): "潍坊",
    ("Shandong", "Weihai"): "威海",
    ("Shandong", "Yantai"): "烟台",
    ("Shandong", "Zibo"): "淄博",
    ("Shanghai Municipality", "Shanghai"): "上海",
    ("Shanxi", "Changzhi"): "长治",
    ("Shanxi", "Datong"): "大同",
    ("Shanxi", "Jincheng"): "晋城",
    ("Shanxi", "Linfen"): "临汾",
    ("Shanxi", "Taiyuan"): "太原",
    ("Shanxi", "Yuncheng"): "运城",
    ("Sichuan", "Chengdu"): "成都",
    ("Sichuan", "Deyang"): "德阳",
    ("Sichuan", "Leshan"): "乐山",
    ("Sichuan", "Luzhou"): "泸州",
    ("Sichuan", "Meishan"): "眉山",
    ("Sichuan", "Mianyang"): "绵阳",
    ("Sichuan", "Nanchong"): "南充",
    ("Sichuan", "Yaan"): "雅安",
    ("Sichuan", "Yibin"): "宜宾",
    ("Sichuan", "Zigong"): "自贡",
    ("Tianjin Municipality", "Tianjin"): "天津",
    ("Tibet", "Chamdo"): "昌都",
    ("Tibet", "Lhasa"): "拉萨",
    ("Tibet", "Nagqu"): "那曲",
    ("Tibet", "Nyingchi"): "林芝",
    ("Tibet", "Shannan"): "山南",
    ("Tibet", "Shigatse"): "日喀则",
    ("Xinjiang", "Hami"): "哈密",
    ("Xinjiang", "Karamay"): "克拉玛依",
    ("Xinjiang", "Turpan"): "吐鲁番",
    ("Xinjiang", "Urumqi"): "乌鲁木齐",
    ("Yunnan", "Baoshan"): "保山",
    ("Yunnan", "Kunming"): "昆明",
    ("Yunnan", "Lijiang"): "丽江",
    ("Yunnan", "Lincang"): "临沧",
    ("Yunnan", "Pu'er"): "普洱",
    ("Yunnan", "Qujing"): "曲靖",
    ("Yunnan", "Yuxi"): "玉溪",
    ("Yunnan", "Zhaotong"): "昭通",
    ("Zhejiang", "Hangzhou"): "杭州",
    ("Zhejiang", "Huzhou"): "湖州",
    ("Zhejiang", "Jiaxing"): "嘉兴",
    ("Zhejiang", "Jinhua"): "金华",
    ("Zhejiang", "Lishui"): "丽水",
    ("Zhejiang", "Ningbo"): "宁波",
    ("Zhejiang", "Quzhou"): "衢州",
    ("Zhejiang", "Shaoxing"): "绍兴",
    ("Zhejiang", "Taizhou"): "台州",
    ("Zhejiang", "Wenzhou"): "温州",
    ("Zhejiang", "Zhoushan"): "舟山",
}


def china_province_display_name(province: str | None, language: str = "en") -> str | None:
    if province is None:
        return None
    if language != "zh-CN":
        return province
    return MAINLAND_CHINA_PROVINCE_DISPLAY_NAMES.get(province, province)


def china_city_display_name(province: str | None, city: str, language: str = "en") -> str:
    if language != "zh-CN" or province is None:
        return city
    return MAINLAND_CHINA_CITY_DISPLAY_NAMES.get((province, city), city)
